fullnameOverride: "register-service"
image:
  repository: minjteck/register-service
  tag: "v9"
ports:
  - containerPort: 5000
env:
  - name: MYSQL_HOST
    value: mysql-service
  - name: MYSQL_DB
    value: enterprise_db
  - name: MYSQL_USER
    value: admin
  - name: MYSQL_PASSWORD
    value: password123
  - name: RABBITMQ_HOST
    value: rabbitmq
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
