apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
  namespace: enterprise-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
