fullnameOverride: "forgot-password-service"
image:
  repository: minjteck/forgot-password-service
  tag: "v9"
ports:
  - containerPort: 5000
env:
  - name: MYSQL_HOST
    value: mysql-service
  - name: MYSQL_DB
    value: enterprise_db
  - name: MYSQL_USER
    value: admin
  - name: MYSQL_PASSWORD
    value: password123
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
