{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise-service.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
{{- if .Values.secret.stringData }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
{{- if .Values.secret.data }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
