apiVersion: v2
name: redis
description: Redis service helm chart
type: application
version: 0.1.0
dependencies:
  - name: enterprise-service
    version: 0.1.0
    repository: "file://../../../charts/enterprise-service"
