apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logout-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minj1992/03-argocd.git
    targetRevision: master
    path: 04-argocd/argocd/manifests/logout
  destination:
    server: https://kubernetes.default.svc
    namespace: enterprise-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
