apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile-microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minj1992/05-argocd-helm.git
    targetRevision: master
    path: charts/enterprise-service
    helm:
      valueFiles:
        - ../../argocd/manifests/profile/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: enterprise-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
