fullnameOverride: "profile-service"
replicaCount: 1
image:
  repository: minjteck/profile-service
  tag: "v9"
ports:
  - containerPort: 5000
env:
  - name: MYSQL_HOST
    value: mysql-service
  - name: MYSQL_DB
    value: enterprise_db
  - name: MYSQL_USER
    value: admin
  - name: MYSQL_PASSWORD
    value: password123
livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
initContainers:
  - name: wait-for-mysql
    image: busybox:1.28
    command: ['sh', '-c', "until nc -zv mysql-service 3306; do echo waiting for mysql; sleep 5; done; sleep 10;"]
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
