apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: enterprise-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
      - name: audit-service
        image: minjteck/audit-service:v6
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq-svc
        - name: REDIS_HOST
          value: redis-svc
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
